# -*- coding: utf-8

"""
This module provides functions to simulate the electricity production by photovoltaic panels.
This file is part of the project OWEFE;
The function for calculating power generated by photovoltaic panels is inspired from Maleki et al. (2015)

"""

import pandas as pd

def calc_pv_te(t_air, ghi, p_rpv, r_ref, n_t, t_c_ref, noct):

    r"""
    Calculates the temperature factor influencing solar energy production
    ----
    Parameters
    ----------
    t_air: ambient air temperature as pd.series or list
    p_rpv: rated Power of photovoltaic panel
    r_ref: solar radiation at reference conditions
    n_t: temperature coefficient of photovoltaic panel
    t_c_ref: cell temperature at reference conditions
    noct: normal operating cell temperature
    ghi: global horizontal irradiance
    Returns
    -------
    pv_te : list of numerical values:
         temperature coefficients for calculating biomass rate

    """
    # Check if input arguments have proper type and length
    if not isinstance(t_air, (list, pd.Series)):
        raise TypeError("Argument 't_air' is not of type list or pd.Series!")
    pv_te = []    # creating a list
    # simplification cell temperature = air temperature; : Calculate cell temperature
    t_c = t_air + ((noct-20)/800)*ghi
    print("printing t_air")
    print(max(t_air))
    print(min(t_air))
    print("ghi")
    print(max(ghi))
    print(min(ghi))
    print("printing t_c")
    print(max(t_c))
    print(min(t_c))
    pv_te = p_rpv*(1/r_ref)*(1+n_t*(t_c-t_c_ref))
    print(max(pv_te))
    print(min(pv_te))
    return pv_te
